pipeline {
    // Docker agent for build
    agent {
        docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        // Build stage
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }

        //Test stage
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }

        // Deliver stage
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }

        // Build and Publish Image
        stage('Publish') {
            agent none
            steps {
                sh '''
                    pwd
                    docker build -t sourish88/${NAME}:1.0.${BUILD_NUMBER} .
                    docker push sourish88/${NAME}:1.0.${BUILD_NUMBER}
                    docker rmi sourish88/${NAME}:1.0.${BUILD_NUMBER}
                '''
            }            
        }
    }
}
