pipeline {
    agent none
    stages {
        // Build stage
        stage('Build') {
            // Docker agent for build
            agent {
                docker {
                    image 'maven:3-alpine'
                    args '-v /root/.m2:/root/.m2'
                }
            }
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }

        //Test stage
        stage('Test') {
            // Docker agent for build
            agent {
                docker {
                    image 'maven:3-alpine'
                    args '-v /root/.m2:/root/.m2'
                }
            }
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }

        // Deliver stage
        stage('Deliver') {
            // Docker agent for build
            agent {
                docker {
                    image 'maven:3-alpine'
                    args '-v /root/.m2:/root/.m2'
                }
            }
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }

        // Build and Publish Image
        stage('Publish') {
            agent {
                docker{
                    image 'docker:dind'
                }
            }
            steps {
                sh '''
                    pwd
                    docker build -t sourish88/${NAME}:1.0.${BUILD_NUMBER} .
                    docker push sourish88/${NAME}:1.0.${BUILD_NUMBER}
                    docker rmi sourish88/${NAME}:1.0.${BUILD_NUMBER}
                '''
            }            
        }
    }
}
